# Funding configuration for vellora.
# vellora does not currently accept sponsorships. When that changes, uncomment
# and fill in the relevant platform(s) below. See:
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [diomalta]            # GitHub Sponsors username(s)
# patreon: # Patreon username
# open_collective: # Open Collective slug
# ko_fi: # Ko-fi username
# tidelift: # platform-name/package-name
# custom: # ["https://example.com/donate"]
